# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kete_translatable_content}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Walter McGinnis"]
  s.date = %q{2010-05-04}
  s.description = %q{Kete Translatable Content is a gem that is an add-on for Kete web applications that takes advantage of the mongo_translatable gem functionality. As you would expect, you use it to add the ability to translate content in your Kete web site.}
  s.email = %q{walter@katipo.co.nz}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "README.rdoc.orig"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/views/topics/_content_wrapper_start.rhtml",
     "config/routes.rb",
     "config/translatables.yml",
     "generators/kete_translatable_content_migration/USAGE",
     "generators/kete_translatable_content_migration/kete_translatable_content_migration_generator.rb",
     "generators/kete_translatable_content_tests/USAGE",
     "generators/kete_translatable_content_tests/kete_translatable_content_tests_generator.rb",
     "generators/kete_translatable_content_tests/templates/configure_kete_content_translation_controller_and_routes_test.rb",
     "generators/kete_translatable_content_tests/templates/configure_kete_content_translation_test.rb",
     "generators/kete_translatable_content_tests/templates/kete_translatable_content_helper_test.rb",
     "generators/kete_translatable_content_tests/templates/kete_translatable_content_migration_test.rb",
     "generators/kete_translatable_content_tests/templates/kete_translations_test.rb",
     "kete_translatable_content.gemspec",
     "lib/configure_kete_content_translation.rb",
     "lib/kete_translatable_content.rb",
     "lib/kete_translatable_content_helper.rb",
     "lib/reload_baskets_per_request.rb",
     "lib/tasks/kete_translatable_content.rake",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/kete/kete_translatable_content}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An add-on to the Kete application to provide content translations.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mongo_translatable>, [">= 0"])
    else
      s.add_dependency(%q<mongo_translatable>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongo_translatable>, [">= 0"])
  end
end

